USE ROLE {{ environment }}_ADMIN_FR;
USE DATABASE DB_RAW_{{ environment }};
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS TEST_SCHEMACHANGE (
    ID INT,
    NAME STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);