-- 3. Crear DB y Schema para schemachange
USE ROLE {{ environment }}_ADMIN_FR;
USE WAREHOUSE COMPUTE_WH;
CREATE DATABASE IF NOT EXISTS DB_SOURCE_{{ environment }};
CREATE DATABASE IF NOT EXISTS DB_ADMIN_{{ environment }};
-- RAW
CREATE DATABASE IF NOT EXISTS DB_RAW_{{ environment }};
-- SILVER
CREATE DATABASE IF NOT EXISTS DB_SILVER_{{ environment }};
-- GOLD
CREATE DATABASE IF NOT EXISTS DB_GOLD_{{ environment }};

