USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS "RM_ADMIN_{{ environment }}" WITH CREDIT_QUOTA = 1000
    TRIGGERS ON 90 PERCENT DO NOTIFY
             ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE WH_ADMIN_{{ environment }}
SET RESOURCE_MONITOR = RM_ADMIN_{{ environment }};