-- 3. Crear DB y Schema para schemachange
USE ROLE {{ environment }}_ADMIN_FR;

CREATE SCHEMA IF NOT EXISTS DB_SOURCE_{{ environment }}.STAGING;
CREATE SCHEMA IF NOT EXISTS DB_ADMIN_{{ environment }}.SCHEMACHANGE;
CREATE SCHEMA IF NOT EXISTS DB_ADMIN_{{ environment }}.LOGS;
CREATE SCHEMA IF NOT EXISTS DB_RAW_{{ environment }}.RAW;
CREATE SCHEMA IF NOT EXISTS DB_SILVER_{{ environment }}.SILVER;
CREATE SCHEMA IF NOT EXISTS DB_GOLD_{{ environment }}.GOLD;
